### ISSUE TITLE
bad indent with cython

### ISSUE THREAD

**Issue by jiajunhuang** [hynek/vim-python-pep8-indent#66]
```cython
cdef void foo(
        i
)
```

but not

```
cdef void foo(
    i
)
```

**Comment by anntzer** [comment]
This is not different from regular python indents, which this plugin also sets to
```
def foo(
        i
): ...
```
(i.e., 8 spaces) in order to avoid having the same indent as the block below.

Now it is correct that Cython has both the form with a final colon (as in Python) and without (i.e., a function declaration, similar to typehint stub files), but when the indent is made we don't know yet what the user is going to do, so defaulting to 8 spaces seems good enough.
